# Generated by Django 4.2.3 on 2023-07-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_photoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoimage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoimage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
